### ISSUE TITLE
any way to remove css asset load if !is_single

### ISSUE THREAD

**Issue by chuckreynolds** [Benunc/better-click-to-tweet#14]
`...../plugins/better-click-to-tweet/assets/css/styles.css`

**Comment by Benunc** [comment]
Just saw this request. no, there's not a way that I know of to remove that stylesheet. And if you removed it from all non-single pages anywhere where the shortcode is placed (widgets, sidebars, archives, etc) would not work correctly. I welcome PRs that try to solve this, but I am not going to attempt it.
