### ISSUE TITLE
Plugin deletes/add options in every request

### ISSUE THREAD

**Issue by igmoweb** [Benunc/better-click-to-tweet#16]
In every page load, the plugin adds and deletes a few options to check which stylesheet should be loaded.

I've prepared a PR that prevents that: https://github.com/Benunc/better-click-to-tweet/pull/15

**Comment by Benunc** [comment]
@igmoweb I mentioned this in the PR, but can you submit that PR against the issue branch associated with this issue so that I can test it in my test install?

Thanks so much for the help!

**Comment by Benunc** [comment]
I figured out a way to do it myself. I am going to run some tests, and will let you know. Thanks again!

**Comment by Benunc** [comment]
Thanks so much! I just (finally) got around to fully testing this with my premium addon, and it works flawlessly. It's now merged into master, and a part of the .org repo (version 5.3)
