### ISSUE TITLE
Allow Google Analytics UTM tags

### ISSUE THREAD

**Issue by cklosowski** [Benunc/better-click-to-tweet#2]
I think it'd be a great addition to add UTM query string vars to the links, so people can see the impact of the Better Click to Tweet in Google Analytics.

I'd be happy to write up a PR for this if you are open to it @Benunc

**Comment by Benunc** [comment]
Absolutely open to that. Thanks!

**Comment by shakaran** [comment]
@cklosowski BUMP, do you have some PR for this feature?

**Comment by Benunc** [comment]
I am going to close this, though I am looking into an add-on that will add this functionality, to prevent it from being bloat on users who aren't interested.
