### ISSUE TITLE
Move BCTT settings into the Settings Menu

### ISSUE THREAD

**Issue by aurooba** [Benunc/better-click-to-tweet#20]
I love this plugin, saves time on client projects! What I don't like is the settings being on the main level of the WordPress main menu. This should be a sub menu item within _Settings_ or within _Tools_, it's not like you have to visit this page a lot once you've set it up. I think it adds unnecessary clutter when otherwise this is a concise and well done plugin.

**Comment by elvismdev** [comment]
+1 to that

**Comment by Benunc** [comment]
Thanks for the comment here (and sorry for my abysmal turnaround on it. 

The main reason why I made it a top level menu item is that my premium add-on requires licencing, and there's no way to nest the licenses another level deeper in the settings. 

I recognize that I could put the licenses on a page that is the same level deep as the setting page itself, but I've just not gotten around to doing that. #sideGigProblems

Here's a PHP snippet you could throw into a must-use plugin to make that menu item go away:

```
add_action('admin_head', 'my_custom_admin_css');

function my_custom_admin_css() {
    echo '<style>
    #toplevel_page_better-click-to-tweet {
    display:none;
}
  </style>';
}
```
