### ISSUE TITLE
Undefined variable urlcustom

### ISSUE THREAD

**Issue by josueochoa** [Benunc/better-click-to-tweet#54]
Using block without setting a custom URL will trigger a Notice message:

`
Notice: Undefined variable: urlcustom in /path-to-plugin/better-click-to-tweet/assets/block/init.php on line 81
`

Something like this could fix this issue:
`
$urlcustom = ( isset( $urlcustom ) ? $urlcustom : '' );
`

**Comment by Benunc** [comment]
Thanks for the heads up here, I am working on a patch for this issue.

Thanks!

**Comment by Benunc** [comment]
Version 5.8.2 will resolve this issue, and it is compiling to release as I type this. Thanks!
