### ISSUE TITLE
Spaces added instead of keeping zero-width spaces

### ISSUE THREAD

**Issue by sbbic** [Benunc/better-click-to-tweet#6]
If you use a language like Khmer that uses zero-width spaces (U+200B) instead of real spaces the plugin seems to strip them and place real spaces instead. Any way this could be fixed?

The way it should be: «ខ្ញុំ​សោកស្ដាយ​ណាស់​ដែល​ខ្ញុំ​គ្មាន​អ្វី​សេសសល់​ថ្វាយ​ទៅ​ទ្រង់​ទៀត»
The way it is now: «ខ្ញុំ សោកស្ដាយ ណាស់ ដែល ខ្ញុំ គ្មាន អ្វី សេសសល់ ថ្វាយ ទៅ ទ្រង់ ទៀត»

Example site: http://plovpit.com/2016/04/08/forsake-all/

Thanks!

**Comment by Benunc** [comment]
Hi there, sorry for the delay. I copy/pasted that line into the shortcode generator, and it appears to be working correctly. Was this issue resolved for you on a recent WordPress update?
![screen shot 2016-07-07 at 1 05 35 pm](https://cloud.githubusercontent.com/assets/9629102/16661997/93eb95d0-4443-11e6-8539-6e4ee4fcb62d.png)
![screen shot 2016-07-07 at 1 05 21 pm](https://cloud.githubusercontent.com/assets/9629102/16661998/93ee40b4-4443-11e6-8bbc-66d5489c1ecb.png)

**Comment by sbbic** [comment]
Yes, it looks fixed. Thanks!
